name: Configurator

on: 
  issues:
     types: [opened]

jobs:
  commentNewIssue:
    name: Comment New Issue
    if: contains(github.event.issue.labels.*.name, 'configuration')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "New issue ${{ github.event.issue.title }} from @${{ github.event.issue.user.login }} "
      - run: echo "${{ github.event.issue.body }}" > world.txt
      - name: attach file
        uses: actions/upload-artifact@v3
        with:
         path: world.txt
